### PR TITLE
Fix displaying Windows alternate data streams in target-shell

### PR DESCRIPTION
**Pull request by pyrco**
(DIS-1844)

### CODE REVIEW

**Comment by pyrco** [comment]
@Schamper I couldn't find a more elegant way to determine whether the file has Windows attributes. Maybe you know of a way?

**Comment by Schamper** [comment]
Hmm yeah normally you'd do something like `entry.fs.__fstype__ == "ntfs"`. That should normally work on `RootFilesystemEntry` objects using `rootfs_entry.entries.fs.__fstype__`, however I believe that `EntryList` (https://github.com/fox-it/dissect.target/blob/main/dissect/target/filesystem.py#L1218) is buggy atm which is why it doesn't work.

I would prefer a approach that doesn't require importing from `dissect.ntfs`, because this creates a hard requirement on `dissect.ntfs` for `target-shell`.

**Comment by pyrco** [comment]
Looks like the `_sub` property of `EntryList` was the culprit. I removed it completely as there was no immediate use for it.

**Comment by Schamper** [comment]
Ahh yes I remember now, that sub attribute was initially meant to be a shortcut to the underlying `FilesystemEntry.entry` attribute, i.e. the implementation specific entry object. However I don't think it ever actually ended up being used as such.

**Review by Schamper — APPROVED** [review]

**Pull request merged**
