### PR TITLE
Fix velociraptor loader c folder

### PR DESCRIPTION
**Pull request by Zawadidone**
#184 hardcode the `C.` folder

### CODE REVIEW

**Comment by Zawadidone** [comment]
Are the made adjustments okay?

**Comment by Schamper** [comment]
I've been thinking about alternative solutions to this with the discussion of #184 in mind and I think I found a decent alternative.

I can make a code suggestion to your branch if you'd like, but basically:
- Rename `map_dirs` in `dir.py` to `find_and_map_dirs`
- Move the loop (from `for path in dirs:` onwards) to a new function `map_dirs(target: Target, dirs: list[Path], alt_separator: str, case_sensitive: bool, **kwargs)`
- Use this new `map_dirs` to map all the volumes correctly in the velociraptor loader, including the volume shadow copies

I think this should work with your intended behavior, as well as making those functions a bit more flexible.

Let me know if you want me to make these changes or if you want to make them yourself.

**Comment by Zawadidone** [comment]
Yes can you make this change.

**Comment by Schamper** [comment]
I pushed my proposed changes, let me know if this approach works for you.

**Comment by Zawadidone** [comment]
Thanks, yes this approach works and nice way of using a list of directories instead of the hardcoded string `C.`.

**Pull request merged**
