### PR TITLE
Feature/proxmox implementation

### PR DESCRIPTION
**Pull request by otnxSl**
Added Support for systems running Proxmox Virtual Environment using the default ext4 filesystem configuration.

### CODE REVIEW

**Comment by Horofic** [comment]
Hey @otnxSl. Thank you for your contribution, looks like quite some work went into this! Please allow us some time to start the review process on this PR. We try to get back to you as soon as possible!

**Comment by otnxSl** [comment]
@DissectBot agree

**Comment by Schamper** [comment]
Depends on #832 for the `/etc/pve/qemu-server` symlink to function.

**Comment by Schamper** [comment]
Test file uploaded in a separate PR because of annoying GitHub bugs with LFS on PR branches: https://github.com/fox-it/dissect.target/pull/833

**Comment by Schamper** [comment]
Will be continued at #837

**Pull request closed without merging**
